### ISSUE TITLE
Shopping Items List

### ISSUE THREAD

**Issue by laurasliwa** [laurasliwa/capstone-grocerease#1]
# Shopping Items List

## Value Proposition

**As a user**

**I want to** browse a well-organised list of shopping items,

**so that** I can easily see what I need to buy.

## Description

![Image](https://github.com/user-attachments/assets/e35b79e6-0e9f-4f48-8dd0-e86b501ae9f5)

## Acceptance Criteria

- The homepage displays a list of shopping items.
- The shopping list is headlined with its purpose.
- Each item listing includes:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
- A counter displays the total number of items currently on the shopping list.
- Each category is visually differentiated, for example, by using different colours.
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [x] Create feature branch `feature/shopping-items-list`
- [x] Inspect and adapt the example data in the [assets folder](./assets/shopping-items.json)
- [x] Replace title in `index.js` to `GrocerEase`
- [x] Create an assests folder with the files ´categories.json` and `shopping-items.json` and copy the data in the corresponding files
- [x] Import the arrays from the assests folder in `_app.js`
- [x] write a function with map using the id and returning the item name, quantity and category
- [x] add a function with a counter for total number of items

- Styling:
- [x] import Google Font
- [x] add a color to each category

----

### 📒 Handout/Link List
- [React with Arrays](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-with-arrays/react-with-arrays.md)
  - Knowing how to use `.map()` to render lists in JSX
  - Understanding how to render items from an array of objects
  - Knowing to add a unique key for list items

**Comment by laurasliwa** [comment]
Notizen:

Map mit key
`function Drinks() {
  const drinks = [
    { id: 0, name: "water" },
    { id: 1, name: "lemonade" },
    { id: 2, name: "coffee" },
    { id: 3, name: "tea" },
  ];

  return (
    <ul>
      {drinks.map(({ id, name }) => (
        <li key={id}>{name}</li>
      ))}
    </ul>
  );
}`

**Comment by laurasliwa** [comment]
Notizen:

- _app.js & index.js nochmal anschauen
- unique identifier/key anschauen
- Map mit key und fragments

**Comment by JessicaLoers** [comment]
Hi Laura. 
well done. There are a few thoughts from my side. 

**Tasks**
- Add an imageUrl for each shopping item, for example from unsplash.com

_You could move this task point to the "Shopping Items Details" user story; you don't need the images beforehand. But it doesn't matter if you want to do the hard work now. 😁_  


 I think it's interesting that your shopping list resembles an Excel sheet—it's a creative approach. 💞

However, I've some concerns regarding usability, especially on mobile devices. Since the items in the list are very closely spaced, it might be challenging to accurately click on an item, particularly on smaller screens. This could make navigation, such as opening a detail page, more difficult, as finger taps on mobile are less precise than mouse clicks.

Perhaps you could consider increasing the spacing between the items or exploring alternative layouts that allow for clearer separation of elements. This could help improve the user experience on mobile devices.
