### ISSUE TITLE
Shopping Item Details

### ISSUE THREAD

**Issue by laurasliwa** [laurasliwa/capstone-grocerease#2]
# Shopping Item Details

## Value Proposition

**As a user**

**I want to** access detailed information about each item in my shopping list,

**so that** I can make informed decisions about what to buy.

## Description

![Image](https://github.com/user-attachments/assets/6f042c81-ec7a-4139-b833-edbdc3daa399)

## Acceptance Criteria

- Each item in the shopping list has a link to a details page.
- Each details page contains:
  - Shopping item name
  - Shopping item image
  - Shopping item quantity
  - Shopping item category
  - Shopping item comments
- The detailed view includes a “back” link, allowing users to easily navigate back to the shopping list.

## Tasks

- [x] Create feature branch `feature/shopping-item-details`
- [x] Inspect and adapt the example data in the [assets folder](./assets/shopping-items.json)
  - [x] Add an `imageUrl` for each shopping item, for example from [unsplash.com](unsplash.com). You first need the image in the User Story [Shopping Item Details](./shopping-item-details.md)
- [x] create page for item details 
- [x] background-color is the category color
- [x] item image displayed on the details page under quantity, name and category
- [x] comments are displayed under the image
- [x] implement dynamic routing

### 📒 Handout/Link List
- [next-dynamic-routes](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/nextjs-dynamic-routes/nextjs-dynamic-routes.md)
  - Knowing implement dynamic paths - for the details page of a item
  - Knowing how to generate links dynamically - link to a details page
