### ISSUE TITLE
Update Shopping Item

### ISSUE THREAD

**Issue by laurasliwa** [laurasliwa/capstone-grocerease#5]
# Update Shopping Item

## Value Proposition

**As a user**

**I want to** edit existing shopping items in my shopping list,

**so that** I can correct errors or update information as needed.

## Description

![Image](https://github.com/user-attachments/assets/06274fd8-e8b6-43e2-961b-4e4315a3265d)

## Acceptance Criteria

- Each shopping item in the shopping list includes an easily accessible edit option.
- Clicking the edit option opens a form pre-filled with the shopping item’s existing details for modification.
- The form allows for edits to all item details, including:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
  - Shopping item comment
- The following fields are mandatory:
  - Shopping item name
  - Shopping item quantity
  - Shopping item category
- The form includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty mandatory fields are blocked, with validation messages indicating the missing required fields.
- Upon confirming the save, the user is redirected back to the shopping list, and the changes are saved and reflected.

## Tasks

- [ ] Create feature branch `feature/update-shopping-item`
- [ ] The category options are listed in the [`categories.json`](./assets/categories.json) file
- [ ] Add Edit svg and render button in ShoppingItem Component
- [ ] Add functionality to pre-fill `Form` component and jump to top of page to edit the ShoppingItem
- [ ] ShoppingItem Name, Category and Quantity are still mandatory
- [ ] Include save and cancel buttons in the form

> 💡 It is not yet possible to edit images at this stage.

### 📒 Handout/Link List
- [react-state-2: Handling Form Data](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-2/react-state-2.md#handling-form-data)
- [react-state-3: Updating Arrays of Objects in State / replacing an object](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-3/react-state-3.md#replacing-an-object)
- React Documentation [Providing an initial value for an input](https://react.dev/reference/react-dom/components/input#providing-an-initial-value-for-an-input)
