### ISSUE TITLE
Mark Item as Purchased

### ISSUE THREAD

**Issue by laurasliwa** [laurasliwa/capstone-grocerease#6]
# Mark Item as Purchased

## Value Proposition

**As a user**

**I want to** mark shopping items as purchased,

**so that** I can keep track of what I have already bought and what is still needed.

## Description

![Image](https://github.com/user-attachments/assets/75756673-a6b8-4346-837a-55d079b8e843)

## Acceptance Criteria

- Each shopping item in the shopping list includes a checkbox to mark the item as purchased.
- When an item is marked as purchased, it is moved to a separate “Purchased Items” section below the shopping list.
- The “Purchased Items” section displays purchased items with a clear visual distinction (e.g., greyed out, strikethrough, etc.).
- The last item marked as purchased appears at the top of the “Purchased Items” section.
- Users can unmark purchased items by clicking the checkbox again.
- Unmarking an item moves it back to the shopping list.
- The shopping list and “Purchased Items” section both support vertical scrolling to accommodate multiple entries.
- The number of items in both sections is clearly displayed.
- If all items in the shopping list are marked as purchased, a message is displayed indicating that all items have been purchased.

## Tasks

- [ ] Create feature branch `feature/mark-item-purchased`
- [ ] implement checkmark icon for each item
- [ ] useState for purchased/unpurchased state into the `shoppingItem` (with key `purchased: true/false`)
- [ ] checkmark icon gets filled when checked
- [ ] component for purchased items list with a counter
- [ ] purchased item names with strikethrough
- [ ] no purchased items in the list has a message displayed indicating that

**Comment by F-Kirchhoff** [comment]
Hey Laura,
die Überschrift von den Tasks hat irgendwie den falschen Text bekommen, bitte ändere das noch um. Des weiteren würde ich dir sehr ans Herz legen, den purchased state direkt in deine items mit einzubauen, also dass jedes Item einen extra key `purchased: true/false` erhält. Ein zweiter State, der diesen Zustand trackt würde die App sehr komplex und fehleranfällig machen. Indem du das purchased direkt auf jedem Item speicherst sind die Daten immer zusammen und du musst dir keine Gedanken um das synchen oder up to date halten zwischen den beiden States machen.
